
# Name of the project
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# The configuration below will override models setting to be materialized as views or tables. 
models:
  +transient: false
  my_new_project:
    # Applies to all files under models/example/
    staging:
      +materialized: table
      +database: "SILVER_DB"
      api_socrata:
        +schema: api_socrata
      
    marts:
      +materialized: table
      +database: "GOLD_DB"
      core:
        +schema: core

